routes/web.php
<?php

use App\Http\Controllers\CacheController;
use App\Http\Controllers\FilesController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\TranslationsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\ProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['admin', 'auth'])->name('dashboard');


Route::prefix("students")->name('students.')->group(function () {
    Route::get('/', [StudentsController::class, 'index']);
    Route::get('/login', [StudentsController::class, 'authenticate'])->name('login');
    Route::get('/logout', [StudentsController::class, 'logout'])->name('logout');
    Route::get('/reg', [StudentsController::class, 'create']);
    Route::post('/store', [StudentsController::class, 'store']);
    Route::post('/attach', [StudentsController::class, 'attach'])->name('students.attach');
    Route::get('/detach/{student}/{subject}', [StudentsController::class, 'detach'])->name('students.detach');
    Route::get('/notat/{student}', [StudentsController::class, 'notat'])->name('students.notat');
});

Route::get('country_villages/{country}', [StudentsController::class, 'countryVillages'])->name('country.villages');

Route::prefix("products")->group(function () {
    Route::get('/', [ProductsController::class, "index"])->name('products_index');
    Route::get('/create', [ProductsController::class, "create"])->name('products_create');
    Route::post('/store', [ProductsController::class, "store"])->name('products_store')->middleware(['auth']);
    Route::get('/show/{product}', [ProductsController::class, "show"])->name('products_show');
    Route::get('/edit/{product}', [ProductsController::class, "edit"])->name('products_edit');
    Route::post('/update', [ProductsController::class, "update"])->name('products_update');
    Route::get('/destroy/{id}', [ProductsController::class, "destroy"])->name('products_destroy');
    Route::get('/by_category/{category}', [ProductsController::class, "byCategory"])->name('products_by_category');
    Route::get('/my_products', [ProductsController::class, "myProducts"])->name('my_products')->middleware(['auth']);
    Route::get('/accessor/{id}/{qty}', [ProductsController::class, "accessor"])->name('accessor');
    Route::get('/mutator/{id}/{price}/{qty}', [ProductsController::class, "mutator"])->name('mutator')->where('price', '[0-9]+');
    Route::get('/place_order', [ProductsController::class, 'orderPlaced'])->name('place_order');
});

Route::prefix("files")->group(function () {

    Route::get('ruaje', [FilesController::class, 'ruaje'])->name('ruaje');
    Route::get('db2csv', [FilesController::class, 'db2csv'])->name('db2csv');
    Route::get('lexoje', [FilesController::class, 'lexoje'])->name('lexoje');
    Route::get('linku', [FilesController::class, 'linku'])->name('linku')->middleware(['auth']);
    Route::get('url', [FilesController::class, 'url'])->name('url');
    Route::get('kopjo', [FilesController::class, 'kopjo'])->name('kopjo');
    Route::get('form', [FilesController::class, 'form'])->name('form')->middleware('auth');
    Route::post('submit_form', [FilesController::class, 'submitForm'])->name('files.submit_form')->middleware('auth');
    Route::get('product/{id}', [FilesController::class, 'product'])->name('files.product');
    Route::get('delete/{id}', [FilesController::class, 'delete'])->name('files.delete');
});


Route::prefix('shop')->group(function() {
    Route::get('add', [ShopController::class, 'add'])->name('shop.add');
    Route::get('read', [ShopController::class, 'read'])->name('shop.read');
    Route::get('push', [ShopController::class, 'push'])->name('shop.push');
    Route::get('pull', [ShopController::class, 'pull'])->name('shop.pull');
    Route::get('inc', [ShopController::class, 'inc'])->name('shop.inc');
    Route::get('process', [ShopController::class, 'process'])->name('shop.process');
    Route::get('flash', [ShopController::class, 'flash'])->name('shop.flash');
    Route::get('emptycart', [ShopController::class, 'emptycart'])->name('shop.emptycart');
    Route::get('dalja', [ShopController::class, 'dalja'])->name('shop.dalja');
    Route::get('resp', [ShopController::class, 'resp'])->name('shop.resp');
    Route::get('kuki', [ShopController::class, 'kuki'])->name('shop.kuki');
    Route::get('kuki2', [ShopController::class, 'kuki2'])->name('shop.kuki2');
});


Route::prefix('cache')->group(function() {
    Route::get('put', [CacheController::class, 'ruaje'])->name('cache.put');
    Route::get('get', [CacheController::class, 'lexoje'])->name('cache.get');
    Route::get('query', [CacheController::class, 'query'])->name('cache.query');
});

Route::get('mirembajtja/{id}',[CacheController::class, 'mirembajtja']);

Route::get('/test', [StudentsController::class, "test"]);
Route::get('/db', [StudentsController::class, "db"]);

Route::get('/report', function () {
    return view('annual_report');
})->middleware('auth.basic');


Route::get('{lang}/page', [TranslationsController::class, 'page'])->name('translations.page');
Route::get('{lang}/details/{id}', [TranslationsController::class, 'details'])->name('translations.details');

require __DIR__ . '/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;

    public $timestamps = true;

    protected $hidden = [
        'secret'
    ];

//    public function getRouteKeyName()
//    {
//        return 'product_slug';
//    }


    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }


    public function getPriceWithVatAttribute()
    {
        return $this->price * 1.15;
    }

    public function getPriceWithVatCurrencyAttribute()
    {
        return $this->price_with_vat . config('custom.default_currency');;
    }

    public function getNewPriceAttribute()
    {
        return "New Discounted Price: " . $this->price_with_vat_currency;
    }

    public function total($t = 1)
    {
        return $this->price_with_vat * $t;
    }

    public function setNewPriceAttribute($value)
    {
        $value = (float)filter_var($value, FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
        $this->attributes['price'] = $value * 1.15;
    }

    public function setTotalAttribute($value)
    {
        $this->attributes['total'] = $value['price'] * $value['quantity'] * 1.15;
    }

    public static function calculate($price, $qty)
    {
        return $price * $qty * 1.15;
    }

    public function getProductThumbnailAttribute()
    {
        $filename1 = "products/thumbnails/foto-" . $this->id . ".jpg";
        $filename2 = "products/thumbnails/foto-" . $this->id . ".png";
        if (Storage::exists($filename1)) {
            return "/" . $filename1;
        } elseif (Storage::exists($filename2)) {
            return "/" . $filename2;
        } else {
            return '/products/no-image.png';
        }

    }


    public function getProductImageAttribute()
    {

        $filename1 = "products/foto-" . $this->id . ".jpg";
        $filename2 = "products/foto-" . $this->id . ".png";
        if (Storage::exists($filename1)) {
            return "/" . $filename1;
        } elseif (Storage::exists($filename2)) {
            return "/" . $filename2;
        } else {
            return '/products/no-image.png';
        }

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/annual_report.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Annual report</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet, aut, culpa cum earum eligendi, est ex fuga nihil pariatur porro quae quam unde? Accusantium consequuntur doloremque error quaerat sint veniam?</p>
</body>
</html>

resources/views/country_villages.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Lista e fshaterave te: {{ $country->country_name }}</h1>
@foreach($country->villages as $village)
    <p>{{ $village->village_name }}</p>
@endforeach

</body>
</html>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!


                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/flash.blade.php
@extends('layouts.baza')


@section('content')
    <h1>Pamja nga view</h1>
    @if (session()->has('status'))
        {{ session('status') }}
    @endif
@endsection

resources/views/product.blade.php
@extends('layouts/baza')

@section('head')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"/>
@endsection

@section('content')

    <div class="col-2">
        @if ($product->product_image == '/products/no-image.png')
            <img src="{{ $product->product_thumbnail }}" class="img-fluid">
        @else
            <a data-fancybox="gallery" href="{{ $product->product_image }}">
                <img src="{{ $product->product_thumbnail }}" class="img-fluid">
            </a>
        @endif
    </div>
    <table class="table">
        <tr>
            <th>Emri</th>
            <td><h1>{{ $product->product_name  }}</h1></td>
        </tr>
        <tr>
            <th>Barkodi</th>
            <td>{{ $product->barcode }}</td>
        </tr>
        <tr>
            <th>Cmimi</th>
            <td>{{ $product->price }}</td>
        </tr>
        <tr>
            <th>Data</th>
            <td>{{ $product->created_at }}</td>
        </tr>

        <tr>
            <td>Pershkrimi</td>
            <td>@parsedown($product->description)</td>
        </tr>
    </table>
@endsection

@section('javascript')
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
@endsection

resources/views/report.blade.php
@extends('layouts.baza')


@section('content')
    <h1>Raport</h1>

    <p>{{ $report }}</p>
@endsection

resources/views/upload_form.blade.php
@extends('layouts.baza')


@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="post" action="{{ route('files.submit_form') }}" enctype="multipart/form-data">
        @csrf

        <div>
            <label for="emri">Sheno emrin e produktit:</label>
            <input type="text" name="product_name" id="emri" value="{{ old('product_name', '') }}" class="form-control">
        </div>

        <div>
            <label for="barcode">Sheno barkodin e produktit:</label>
            <input type="text" name="barcode" id="barcode" value="{{ old('barcode', '') }}" class="form-control">
        </div>
        <div>
            <label for="category_id">Kategoria:</label>
            <select id="category_id" name="category_id">
                @foreach($categories as $category)

                    <option
                        @if ($category->id == old('category_id'))
                        selected
                        @endif
                        value="{{ $category->id }}">{{ $category->category_name }}</option>
                @endforeach
            </select>
        </div>

        <div>
            <label for="description">Pershkrimi:</label>
            <textarea id="description" name="description" rows="5"
                      class="form-control">{{ old('description') }}</textarea>
        </div>

        <div>
            <label for="price">Cmimi:</label>
            <input type="text" name="price" id="price" value="{{ old('price', 0) }}" class="form-control">
        </div>
        <div>
            <input type="file" name="profile_picture">
        </div>
        <input type="submit" value="DERGO">

    </form>
@endsection