routes/web.php
<?php

use App\Http\Controllers\CacheController;
use App\Http\Controllers\FilesController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\TranslationsController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\ProductsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['admin', 'auth'])->name('dashboard');


Route::prefix("students")->name('students.')->group(function () {
    Route::get('/', [StudentsController::class, 'index']);
    Route::get('/login', [StudentsController::class, 'authenticate'])->name('login');
    Route::get('/logout', [StudentsController::class, 'logout'])->name('logout');
    Route::get('/reg', [StudentsController::class, 'create']);
    Route::post('/store', [StudentsController::class, 'store']);
    Route::post('/attach', [StudentsController::class, 'attach'])->name('students.attach');
    Route::get('/detach/{student}/{subject}', [StudentsController::class, 'detach'])->name('students.detach');
    Route::get('/notat/{student}', [StudentsController::class, 'notat'])->name('students.notat');
});

Route::get('country_villages/{country}', [StudentsController::class, 'countryVillages'])->name('country.villages');

Route::prefix("products")->group(function () {
    Route::get('/', [ProductsController::class, "index"])->name('products_index');
    Route::get('/create', [ProductsController::class, "create"])->name('products_create');
    Route::post('/store', [ProductsController::class, "store"])->name('products_store')->middleware(['auth']);
    Route::get('/show/{product}', [ProductsController::class, "show"])->name('products_show');
    Route::get('/edit/{product}', [ProductsController::class, "edit"])->name('products_edit');
    Route::post('/update', [ProductsController::class, "update"])->name('products_update');
    Route::get('/destroy/{id}', [ProductsController::class, "destroy"])->name('products_destroy');
    Route::get('/by_category/{category}', [ProductsController::class, "byCategory"])->name('products_by_category');
    Route::get('/my_products', [ProductsController::class, "myProducts"])->name('my_products')->middleware(['auth']);
    Route::get('/accessor/{id}/{qty}', [ProductsController::class, "accessor"])->name('accessor');
    Route::get('/mutator/{id}/{price}/{qty}', [ProductsController::class, "mutator"])->name('mutator')->where('price', '[0-9]+');
    Route::get('/place_order', [ProductsController::class, 'orderPlaced'])->name('place_order');
});

Route::prefix("files")->group(function () {

    Route::get('ruaje', [FilesController::class, 'ruaje'])->name('ruaje');
    Route::get('db2csv', [FilesController::class, 'db2csv'])->name('db2csv');
    Route::get('lexoje', [FilesController::class, 'lexoje'])->name('lexoje');
    Route::get('linku', [FilesController::class, 'linku'])->name('linku')->middleware(['auth']);
    Route::get('url', [FilesController::class, 'url'])->name('url');
    Route::get('kopjo', [FilesController::class, 'kopjo'])->name('kopjo');
    Route::get('form', [FilesController::class, 'form'])->name('form')->middleware('auth');
    Route::post('submit_form', [FilesController::class, 'submitForm'])->name('files.submit_form')->middleware('auth');
    Route::get('product/{id}', [FilesController::class, 'product'])->name('files.product');
    Route::get('delete/{id}', [FilesController::class, 'delete'])->name('files.delete');
});


Route::prefix('shop')->group(function() {
    Route::get('add', [ShopController::class, 'add'])->name('shop.add');
    Route::get('read', [ShopController::class, 'read'])->name('shop.read');
    Route::get('push', [ShopController::class, 'push'])->name('shop.push');
    Route::get('pull', [ShopController::class, 'pull'])->name('shop.pull');
    Route::get('inc', [ShopController::class, 'inc'])->name('shop.inc');
    Route::get('process', [ShopController::class, 'process'])->name('shop.process');
    Route::get('flash', [ShopController::class, 'flash'])->name('shop.flash');
    Route::get('emptycart', [ShopController::class, 'emptycart'])->name('shop.emptycart');
    Route::get('dalja', [ShopController::class, 'dalja'])->name('shop.dalja');
    Route::get('resp', [ShopController::class, 'resp'])->name('shop.resp');
    Route::get('kuki', [ShopController::class, 'kuki'])->name('shop.kuki');
    Route::get('kuki2', [ShopController::class, 'kuki2'])->name('shop.kuki2');
});


Route::prefix('cache')->group(function() {
    Route::get('put', [CacheController::class, 'ruaje'])->name('cache.put');
    Route::get('get', [CacheController::class, 'lexoje'])->name('cache.get');
    Route::get('query', [CacheController::class, 'query'])->name('cache.query');
});

Route::get('mirembajtja/{id}',[CacheController::class, 'mirembajtja']);

Route::get('/test', [StudentsController::class, "test"]);
Route::get('/db', [StudentsController::class, "db"]);

Route::get('/report', function () {
    return view('annual_report');
})->middleware('auth.basic');


Route::get('{lang}/page', [TranslationsController::class, 'page'])->name('translations.page');
Route::get('{lang}/details/{id}', [TranslationsController::class, 'details'])->name('translations.details');

require __DIR__ . '/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    use HasFactory;

    public $timestamps = true;

    protected $hidden = [
        'secret'
    ];

//    public function getRouteKeyName()
//    {
//        return 'product_slug';
//    }


    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }


    public function getPriceWithVatAttribute()
    {
        return $this->price * 1.15;
    }

    public function getPriceWithVatCurrencyAttribute()
    {
        return $this->price_with_vat . config('custom.default_currency');;
    }

    public function getNewPriceAttribute()
    {
        return "New Discounted Price: " . $this->price_with_vat_currency;
    }

    public function total($t = 1)
    {
        return $this->price_with_vat * $t;
    }

    public function setNewPriceAttribute($value)
    {
        $value = (float)filter_var($value, FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION);
        $this->attributes['price'] = $value * 1.15;
    }

    public function setTotalAttribute($value)
    {
        $this->attributes['total'] = $value['price'] * $value['quantity'] * 1.15;
    }

    public static function calculate($price, $qty)
    {
        return $price * $qty * 1.15;
    }

    public function getProductThumbnailAttribute()
    {
        $filename1 = "products/thumbnails/foto-" . $this->id . ".jpg";
        $filename2 = "products/thumbnails/foto-" . $this->id . ".png";
        if (Storage::exists($filename1)) {
            return "/" . $filename1;
        } elseif (Storage::exists($filename2)) {
            return "/" . $filename2;
        } else {
            return '/products/no-image.png';
        }

    }


    public function getProductImageAttribute()
    {

        $filename1 = "products/foto-" . $this->id . ".jpg";
        $filename2 = "products/foto-" . $this->id . ".png";
        if (Storage::exists($filename1)) {
            return "/" . $filename1;
        } elseif (Storage::exists($filename2)) {
            return "/" . $filename2;
        } else {
            return '/products/no-image.png';
        }

    }
}

resources/views/products/attribute.blade.php
@extends('layouts.baza')

@section('content')
    <h1>{{ $product->product_name }}</h1>
    <p>Normal price: {{ $product->price  }}</p>
    <p>With VAT: {{ $product->price_with_vat }}</p>
    <p>{{ $product->new_price }}</p>
    <p>Total: {{ $product->total($qty) }}</p>

@endsection

resources/views/products/by_category.blade.php
@extends('layouts.baza')

@section('content')
<h1>Category: {{ $category->category_name }}</h1>

@include('products/partials/list')

@endsection

resources/views/products/create.blade.php
@extends('layouts.baza')

@section('content')
<div style="background-color: #ffb597">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    @endif
</div>
<form method="post" action="{{ route('products_store') }}">
    @csrf
    <p>Emri: <input type="text" name="product_name" value="{{ old('product_name') }}"></p>
    <p>Barkodi: <input type="text" name="barcode" value="{{ old('barcode') }}" maxlength="13" minlength="13"></p>
    <p>Price: <input type="text" name="price" value="{{ old('price') }}"></p>

    <div>
        <p>Description</p>
        <textarea name="description" class="form-control" rows="10">{{ old('description') }}</textarea>
    </div>
    <div>
        <select name="category_id">
            <option value="0">Zgjedhe kategorine:</option>
            @foreach($categories as $category)
                <option
                    @if ($category->id == old('category_id')) selected @endif
                    value="{{ $category->id }}">{{ $category->category_name }}</option>
            @endforeach
        </select>
    </div>

    <input type="submit" value="REGJISTRO">
</form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.baza')

@section('content')
<div style="background-color: #ffb597">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    @endif
</div>
<form method="post" action="{{ route('products_update') }}">
    @csrf
    <input type="hidden" name="product_id" value="{{ $product->id }}">
    <p>Emri: <input class="form-control" type="text" name="product_name" value="{{ old('product_name', $product->product_name) }}"></p>
    <p>Barkodi: <input class="form-control" type="text" name="barcode" value="{{ old('barcode', $product->barcode) }}" maxlength="13" minlength="13"></p>
    <p>Price: <input class="form-control" type="text" name="price" value="{{ old('price', $product->price) }}"></p>


    <div>
        <select name="category_id" class="form-select" >
            <option value="0">Zgjedhe kategorine:</option>
            @foreach($categories as $category)
                <option
                    @if ($category->id == old('category_id', $product->category_id)) selected @endif
                value="{{ $category->id }}">{{ $category->category_name }}</option>
            @endforeach
        </select>
    </div>

    <input type="submit" class="btn btn-primary" value="REGJISTRO">
</form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.baza')

@section('content')
<a href="{{ route('products_create') }}">Add new product</a>
@include('products/partials/list')

    {{ $products->links() }}

@endsection

@section('sidebar')

    <h4>Sidebar</h4>
@endsection

resources/views/products/my_products.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Produktet e mia</h1>

@foreach(Auth::user()->products as $product)
    <p>{{ $product->product_name }}</p>
@endforeach
</body>
</html>

resources/views/products/show.blade.php
@extends('layouts/baza')

@section('content')
    <table class="table">
        <tr>
            <th>Emri</th>
            <td><h1>{{ $product->product_name  }}</h1></td>
        </tr>
        <tr>
            <th>Barkodi</th>
            <td>{{ $product->barcode }}</td>
        </tr>
        <tr>
            <th>Cmimi</th>
            <td>{{ $product->price }}</td>
        </tr>
        <tr>
            <th>Data</th>
            <td>{{ $product->created_at }}</td>
        </tr>

        <tr>
            <td>Pershkrimi</td>
            <td>@parsedown($product->description)</td>
        </tr>
    </table>

    @json($lista)

    @php
        echo date("d.m.Y", time());
    @endphp
@endsection